version: 0.2       
phases:
  install:
    commands:
      - ./build-layers || exit 1
      - npm-recursive-install --production
  build:
    commands:
      - stackbuilder-py build || exit 1
      - aws cloudformation package  --template-file template.yaml --output-template-file packaged-template.json --s3-bucket stack-builds-oregon --use-json || exit 1
artifacts:
  files:
    - packaged-template.json
    - template-config-dev.json
    - template-config-staging.json
    - template-config-prod.json